kind: Service                             
apiVersion: v1
metadata:
  name: mrdevops
  labels:
    app: mrdevops
spec:
  ports:
    - port: 8080                             
      targetPort: 82                    
      nodePort:  8080
  selector:
    app: mrdevops                    
  type: LoadBalancer 
