kind: Service                             
apiVersion: v1
metadata:
  name: mrdevops
  labels:
    app: mrdevops
spec:
  ports:
    - port: 7080                               
      targetPort: 90                    
      nodePort: 31200
  selector:
    app: mrdevops                    
  type: LoadBalancer 
